# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('movement_type', models.CharField(choices=[('b', 'balance'), ('c', 'cardio'), ('d', 'dance'), ('f', 'flexibility'), ('o', 'other'), ('s', 'strength'), ('l', 'stretch'), ('w', 'weights'), ('y', 'yoga')], default='o', max_length=1)),
                ('difficulty', models.CharField(choices=[('n', 'none'), ('b', 'beginner'), ('i', 'intermediate'), ('a', 'advanced')], default='n', max_length=1)),
                ('demo_url', models.CharField(blank=True, max_length=2000)),
                ('timestamp_last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silly_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('workout_data', jsonfield.fields.JSONField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
