# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='title',
            new_name='movement_name',
        ),
        migrations.AlterField(
            model_name='movement',
            name='difficulty',
            field=models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
