# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0002_auto_20170811_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='difficulty',
            field=models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='n', max_length=100),
        ),
    ]
