# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickfitapp', '0002_exercise_exercise_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('movement_type', models.CharField(choices=[('w', 'Weight Lifting'), ('d', 'dance'), ('c', 'cardio'), ('o', 'Others')], default='o', max_length=1)),
                ('timestamp_last_updated', models.DateField(auto_now=True)),
                ('timestamp_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
