# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0003_auto_20170808_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='author',
            new_name='author_id',
        ),
        migrations.AddField(
            model_name='movement',
            name='demo_url',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('b', 'balance'), ('c', 'cardio'), ('d', 'dance'), ('f', 'flexibility'), ('o', 'other'), ('s', 'strength'), ('l', 'stretch'), ('w', 'weights'), ('y', 'yoga')], default='o', max_length=1),
        ),
    ]
