# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0003_auto_20170811_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
