# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0004_auto_20170811_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='author',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
