# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0006_auto_20170811_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='silly_username',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_phrase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='proxy_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
