# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0007_auto_20170812_0348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
