# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0007_auto_20170808_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='author_id',
            new_name='author',
        ),
    ]
