# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 05:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0012_auto_20170808_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movement',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='timestamp_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='athlete',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='timestamp_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
