# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='difficulty',
            field=models.CharField(choices=[('n', 'none'), ('b', 'beginner'), ('i', 'intermediate'), ('a', 'advanced')], default='n', max_length=1),
        ),
    ]
