# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 03:48
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0005_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_data',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
