# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0011_auto_20170808_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
