# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0012_auto_20170808_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silly_username', models.CharField(max_length=100)),
            ],
        ),
    ]
