# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0013_auto_20170810_0509'),
        ('quickfitapp', '0014_movement_difficulty'),
    ]

    operations = [
    ]
