# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0015_merge_20170810_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
