# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickfitapp', '0016_auto_20170810_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
